### ISSUE TITLE
Does not compile with TypeScript 2.9

### ISSUE THREAD

**Issue by bard** [xdave/ink-typescript-redux-test#1]
```
$ ts-node -v
ts-node v6.1.0
node v10.2.0
typescript v2.9.1
cache "/tmp/ts-node-d3450f0a164e30b4820b0019ea2b5671d8bd3a0d6145bdd448869f8eeea9ed6a/e59aea318efe24af38a9b0fed1401ad02dcffd6960130b5116e0080d8b7c3c9e"
$ ts-node .

/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:250
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
components/Counter.tsx(13,5): error TS2564: Property 'context' has no initializer and is not definitely assigned in the constructor.

    at createTSError (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:250:12)
    at getOutput (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:358:40)
    at Object.compile (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:545:11)
    at Module.m._compile (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:430:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .tsx] (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:433:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

**Comment by bard** [comment]
Changing https://github.com/xdave/ink-typescript-redux-test/blob/master/components/Counter.tsx#L13 to:

```
context!: Store<State>;
```

Appears to fix it.

**Comment by lipalath-ms** [comment]
@bard What does ! indicate?

**Comment by bard** [comment]
It's the "non-null assertion operator":

> A new ! post-fix expression operator may be used to assert that its operand is non-null and non-undefined in contexts where the type checker is unable to conclude that fact. Specifically, the operation x! produces a value of the type of x with null and undefined excluded. Similar to type assertions of the forms <T>x and x as T, the ! non-null assertion operator is simply removed in the emitted JavaScript code.

https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator

**Comment by lipalath-ms** [comment]
Thank you!
